namespace: ics
name: common
version: 2.0.0
readme: README.md
authors:
  - ICS Infrastructure Team
description: >-
  ICS Common Ansible Collection providing reusable infrastructure automation
  components for multi-customer environments with standardized security,
  monitoring, and deployment patterns.

license:
  - MIT

license_file: LICENSE

tags:
  - infrastructure
  - linux
  - security
  - monitoring
  - hardening
  - backup
  - web
  - automation
  - enterprise

dependencies:
  "community.general": ">=7.0.0"
  "ansible.posix": ">=1.5.0"
  "community.crypto": ">=2.0.0"
  "community.docker": ">=3.0.0"

repository: https://github.com/your-org/ics-ansible-collection
documentation: https://docs.ics.com/ansible-collection
homepage: https://ics.com/automation
issues: https://github.com/your-org/ics-ansible-collection/issues

build_ignore:
  - "*.tar.gz"
  - ".git*"
  - ".github"
  - "tests/output"
  - ".pytest_cache"
  - ".tox"
  - "molecule"
  - ".molecule"
