- name: Restart telegraf
  ansible.builtin.service:
    name: telegraf
    state: restarted

- name: Ensure Telegraf is running
  ansible.builtin.service:
    name: telegraf
    state: started
    enabled: true
